import React from "react"
import Dropdown from "./Dropdown"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Dropdown,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=4130%3A5933",
  {
    props: {
      label: figma.string("Label"),
      value: figma.string("Value"),
      showLabel: figma.boolean("Show Label"),
      description: figma.string("Description"),
      showDescription: figma.boolean("Show Description"),
      state: figma.enum("State", {
        Placeholder: "placeholder",
        Active: "active",
      }),
    },
    example: (props) => <Dropdown />,
  },
)
