import React from "react"
import EventNav from "./EventNav"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  EventNav,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=677%3A4860",
  {
    props: {},
    example: (props) => <EventNav />,
  },
)
