import React from "react"
import IconButton from "./IconButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  IconButton,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=397%3A10151",
  {
    props: {
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Outline: "outline",
      }),
      state: figma.enum("State", {
        Default: "default",
        Disabled: "disabled",
      }),
      size: figma.enum("Size", {
        Medium: "medium",
        Small: "small",
      }),
    },
    example: (props) => <IconButton />,
  },
)
