import React from "react"
import TileCallout from "./TileCallout"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TileCallout,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=788%3A5366",
  {
    props: {
      label: figma.string("Label"),
      value: figma.string("Value"),
      variant: figma.enum("Variant", {
        Subtle: "subtle",
        Highlight: "highlight",
      }),
    },
    example: (props) => <TileCallout />,
  },
)
