import React from "react"
import Avatar from "./Avatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=397%3A9939",
  {
    props: {
      size: figma.enum("Size", {
        "80": "80",
        "56": "56",
        "32": "32",
        "40": "40",
      }),
    },
    example: (props) => <Avatar />,
  },
)
