import React from "react"
import BrandIcon from "./BrandIcon"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BrandIcon,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=670%3A1399",
  {
    props: {
      glyph: figma.enum("Glyph", {
        Home: "home",
        Wind: "wind",
        Sun: "sun",
        Location: "location",
        Map: "map",
        Compass: "compass",
        Close: "close",
        Save: "save",
        Share: "share",
        User: "user",
        Lightning: "lightning",
        Calendar: "calendar",
        Rain: "rain",
        "Frame 2147239245": "frame-2147239245",
        Search: "search",
        "Arrow Back": "arrow-back",
        Caret: "caret",
        Bolt: "bolt",
        Clouds: "clouds",
        "Arrow Down": "arrow-down",
        "Arrow Up": "arrow-up",
        "Arrow Left": "arrow-left",
        "Arrow Right": "arrow-right",
      }),
    },
    example: (props) => <BrandIcon />,
  },
)
