import React from "react"
import TileWeather from "./TileWeather"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TileWeather,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=786%3A3037",
  {
    props: {
      time: figma.string("Time"),
      conditions: figma.string("Conditions"),
      temp: figma.string("Temp"),
      low: figma.string("Low"),
      high: figma.string("High"),
    },
    example: (props) => <TileWeather />,
  },
)
