import React from "react"
import BottomSheet from "./BottomSheet"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BottomSheet,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=2012%3A577",
  {
    props: {
      size: figma.enum("Size", {
        Tall: "tall",
        Default: "default",
      }),
    },
    example: (props) => <BottomSheet />,
  },
)
