import React from "react"
import CardEvent from "./CardEvent"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CardEvent,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=424%3A1729",
  {
    props: {
      showOverlay: figma.boolean("Show Overlay"),
      overlay: figma.string("Overlay"),
      title: figma.string("Title"),
      location: figma.string("Location"),
      time: figma.string("Time"),
      people: figma.string("People"),
      sponsoredEvent: figma.boolean("Sponsored event"),
      size: figma.enum("Size", {
        Large: "large",
        Small: "small",
      }),
    },
    example: (props) => <CardEvent />,
  },
)
