import React from "react"
import CardGuide from "./CardGuide"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CardGuide,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=424%3A1419",
  {
    props: {
      name: figma.string("Name"),
      category: figma.string("Category"),
    },
    example: (props) => <CardGuide />,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CardGuide,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=345%3A20186",
  {
    props: {
      name: figma.string("Name"),
      title: figma.string("Title"),
      location: figma.string("Location"),
      eventIndicator: figma.string("Event indicator"),
    },
    example: (props) => <CardGuide />,
  },
)
