import React from "react"
import Button from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=2031%3A594",
  {
    props: {
      label: figma.string("Label"),
      icon: figma.boolean("Icon"),
      colour: figma.enum("Colour", {
        Brand: "brand",
        "Transparent White": "transparent-white",
        "Transparent Black": "transparent-black",
      }),
      size: figma.enum("Size", {
        Large: "large",
        Medium: "medium",
      }),
    },
    example: (props) => <Button />,
  },
)
