import React from "react"
import SwitchField from "./SwitchField"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SwitchField,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=397%3A10253",
  {
    props: {
      label: figma.string("Label"),
      description: figma.string("Description"),
      showDescription: figma.boolean("Show Description"),
      active: figma.boolean("Active"),
    },
    example: (props) => <SwitchField />,
  },
)
