import React from "react"
import Chip from "./Chip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Chip,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=786%3A4220",
  {
    props: {
      label: figma.string("Label"),
      active: figma.boolean("Active"),
    },
    example: (props) => <Chip />,
  },
)
