import React from "react"
import TileCommunity from "./TileCommunity"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TileCommunity,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=424%3A701",
  {
    props: {
      activity: figma.string("Activity"),
      count: figma.string("Count"),
    },
    example: (props) => <TileCommunity />,
  },
)
