import React from "react"
import SearchInput from "./SearchInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SearchInput,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=799%3A4917",
  {
    props: {
      text: figma.string("Text"),
      state: figma.enum("State", {
        Placeholder: "placeholder",
        Active: "active",
      }),
    },
    example: (props) => <SearchInput />,
  },
)
