import React from "react"
import MapPin from "./MapPin"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MapPin,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=871%3A2742",
  {
    props: {},
    example: (props) => <MapPin />,
  },
)
