import React from "react"
import TileDate from "./TileDate"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TileDate,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=424%3A1717",
  {
    props: {
      month: figma.string("Month"),
      day: figma.string("Day"),
    },
    example: (props) => <TileDate />,
  },
)
