import React from "react"
import TextInput from "./TextInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TextInput,
  "https://www.figma.com/design/PSVZBAMK08FWIqvchjq7ml?node-id=397%3A10222",
  {
    props: {
      dropdown: figma.boolean("Dropdown"),
      label: figma.string("Label"),
      value: figma.string("Value"),
      showLabel: figma.boolean("Show Label"),
      description: figma.string("Description"),
      showDescription: figma.boolean("Show Description"),
      state: figma.enum("State", {
        Default: "default",
        Empty: "empty",
        State3: "state3",
      }),
    },
    example: (props) => <TextInput />,
  },
)
